# [Istruzioni]
# Creazione : docker build -t wasaphoto-frontend:latest -f Dockerfile.frontend . 
# Esecuzione : docker run -it --rm -p 8081:80  wasaphoto-frontend:latest

#--------------------------------------------------------------------------------------------------------#
# [NODE]
# 1) Setting di node:latest come immagine di base da cui partire
# 2) Creazione della cartella src in cui lavorare
# 3) Copia di tutti i files della directory webui all'interno della cartella webui (all'interno della directory di lavoro /src/)
# 4) Cambio della directory di lavoro in "webui"
# 5) Esecuzione del comando per costruire l'app
#--------------------------------------------------------------------------------------------------------#

FROM node:lts as frontend_compiler
WORKDIR /src/
COPY ./webui ./webui
WORKDIR /src/webui/
RUN npm run build-prod

#--------------------------------------------------------------------------------------------------------#
# [NGINX]
# 1) Setting di nginx (versione stable) come immagine di base da cui partire
# 2) Copia della cartella "dist" dal frontend compiler nel percorso per fare hosting dell'app
#--------------------------------------------------------------------------------------------------------#

FROM nginx:stable
COPY --from=frontend_compiler /src/webui/dist /usr/share/nginx/html









